# This workflow configuration is used
# to automate building a public docker image of redstone-node
# and publishing it to the AWS ECR Public

# Learn more: https://github.com/pahud/ecr-public-action

name: Deploy to Amazon ECR Public
on:
  push:
    branches:
      - main
      - push-docker-ecr-public
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ECR public action
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup env variables
        run: |
          echo IMAGE=public.ecr.aws/y7v2w8b2/$(echo ${{github.repository}} | cut -d '/' -f 2) >> "$GITHUB_ENV"
          echo TAG=$(git rev-parse --short=8 HEAD) >> "$GITHUB_ENV"
      - name: Build docker image
        run: |
          docker build -t "$IMAGE:$TAG" .
      - name: Push docker image to ECR public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker push $IMAGE:$TAG
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest
